# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sked', '0001_initial'),
        ('camp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorshiplevel',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorship_levels', to='sked.Event'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='sponsorship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='camp.SponsorshipLevel'),
        ),
        migrations.AddField(
            model_name='emailsubscriber',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_subscribers', to='sked.Event'),
        ),
    ]
